### PR TITLE
Added RTL support for feature request#82

### PR DESCRIPTION
**Pull request by RGabi**
- added RTL (right to left) support for start and end ticks
- defined custom support attribute
- fixed error Sample application uses missing dimens

### CODE REVIEW

**Comment by krazykira** [comment]
@RGabi Can you update the PR. It seems to be stale
@oli107 kindly contact me on my email. I would like to publish new version but i don't think i have the necessary rights

**Comment by OmarKRostom** [comment]
Is this done or what, as I am working on this feature and though about a soon pull request, can you confirm your status please ?

**Comment by krazykira** [comment]
@OmarKRostom  this PR isn't merged as there are conflicts. So please create a new PR

**Comment by krazykira** [comment]
This codebase is outdated and the folder structured got changed after the last update so kindly resolve conflicts and submit new PR

**Pull request closed without merging**
