### PR TITLE
allow pinColor transparency

### PR DESCRIPTION
**Pull request by amoslital**

### CODE REVIEW

**Comment by lital-nanit** [comment]
I added a change that supports alpha value for the pin color in general.
What I actually needed is to only show the pin text without the bubble itself and I thought about several ways to support it:

1. Support any alpha (what is in the P.R).
2. Disable filter only when given android.R.color.transparent.
3. Add a showOnlyPinLabel styleable value.

Hope you'll accept any of these.

**Comment by krazykira** [comment]
@lital-nanit  i like the 3rd approach better. Once you create a PR i will be happy to review it.
@amoslital Maybe you want to do it like @lital-nanit explained (3rd point)

**Comment by amoslital** [comment]
We're actually the same person I just mixed my accounts. Fixed the P.R. Thanks @krazykira .

**Comment by krazykira** [comment]
@amoslital i checked PR #141 and it seems this functionality can be achieved without changing the code by assigning transparency to  `app:mrb_pinColor ` so i will be reverting the commit and merging the other PR. Thankyou for your help anyways
```
        app:mrb_pinColor="@android:color/transparent"/>
```

**Pull request merged**
