### PR TITLE
Implementation of an interface to format the string to appear on the …

### PR DESCRIPTION
**Pull request by busterkikas**
Implementation of an interface to format the string to appear on the pin.
Creating a method that enables and disables the writing of ticks. Useful when you want to make a range of a very large range.

### CODE REVIEW

**Comment by xsorifc28** [comment]
Is this pull request available in the latest release?

**Comment by kjpublic01** [comment]
This would be quite useful to us as well. What's the status?

**Comment by oli107** [comment]
Apologies all, I have been working on a large web project for some time and
have been neglecting android development. I will go through all the PRs in
the next few weeks and reissue a new version.

On 10 September 2015 at 20:45, Ken Jones <notifications@github.com> wrote:

> This would be quite useful to us as well. What's the status?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oli107/material-range-bar/pull/8#issuecomment-139358641>
> .
>

-- 


*## **Email confidentiality notice **##*

*This message is private and confidential. If you have received this 
message in error, please notify us and remove it from your 
system. Blythwood Vets & The Well Animal Clinic may monitor email traffic 
data and also the content of email for the purposes of security.*

*Blythwood Vets is the name under which the surgeries at Bushey, Northwood, 
Stanmore & Hatch End trade but the surgeries are owned by Blythwood 
Veterinary Ltd, a Limited Liability Company registered in England with 
Company No. 07153623, registered office 500 Uxbridge Road, Pinner, Middx, 
HA5 4SL or; in the case of the Bushey surgery, Blythwood Veterinary 
(Bushey) LLP, a Limited Liability Partnership registered in England with 
No. oc368295, registered office 2 High Street, Bushey, Herts WD23 3DN.*

*Well Animal Clinic is the trading name of Well Animal Clinic LLP, a 
Limited Liability Partnership registered in England with No. oc317137, 
registered office 292 West End Lane, London NW6 1LN.*

*A list of members each LLP is open to inspection at their respective 
registered offices.*

*BLYTHWOOD VETS& THE WELL ANIMAL CLINIC*

*“A COMPLETE CARING SERVICE FOR YOUR PET”*

*Visit us at: **www.blythwood.com* <http://www.blythwood.com/>* & **www.wellanimalclinic.com 
<http://www.wellanimalclinic.com/>*

**Comment by oli107** [comment]
Couldn't automatically merge, done manually

**Pull request closed without merging**
