### PR TITLE
Fix usage isues

### PR DESCRIPTION
**Pull request by darius-janusauskas**
- Fix `OnRangeBarChangeListener` callback when tapping on the range bar.
- Fix range check when setting the selected left range value that is equal to the end tick value.

### CODE REVIEW

**Comment by oli107** [comment]
Apologies, I did not see this come through on my notifications. Another PR was requested and I merged it first with the same request. Thanks

**Comment by darius-janusauskas** [comment]
I see that the range value check is fixed, but there was another commit [`1b62d76`](https://github.com/darius-janusauskas/material-range-bar/commit/1b62d763ea0b468005e2716ad545b463911d6a86) that fixed an issue that occurred when tapping on the range-bar.

**Comment by oli107** [comment]
you're absolutely right, sorry. Do you want to do a separate PR for that,
or happy for me to add it in myself?

On 5 February 2015 at 13:11, Darius Janušauskas <notifications@github.com>
wrote:

> I see that the range value check is fixed, but there was another commit
> 1b62d76
> <https://github.com/darius-janusauskas/material-range-bar/commit/1b62d763ea0b468005e2716ad545b463911d6a86>
> that fixed an issue that occurred when tapping on the range-bar.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oli107/material-range-bar/pull/4#issuecomment-73043412>
> .
>

-- 


*## **Email confidentiality notice **##*

*This message is private and confidential. If you have received this 
message in error, please notify us and remove it from your 
system. Blythwood Vets & The Well Animal Clinic may monitor email traffic 
data and also the content of email for the purposes of security.*

*Blythwood Vets is the name under which the surgeries at Bushey, Northwood, 
Stanmore & Hatch End trade but the surgeries are owned by Blythwood 
Veterinary Ltd, a Limited Liability Company registered in England with 
Company No. 07153623, registered office 500 Uxbridge Road, Pinner, Middx, 
HA5 4SL or; in the case of the Bushey surgery, Blythwood Veterinary 
(Bushey) LLP, a Limited Liability Partnership registered in England with 
No. oc368295, registered office 2 High Street, Bushey, Herts WD23 3DN.*

*Well Animal Clinic is the trading name of Well Animal Clinic LLP, a 
Limited Liability Partnership registered in England with No. oc317137, 
registered office 292 West End Lane, London NW6 1LN.*

*A list of members each LLP is open to inspection at their respective 
registered offices.*

*BLYTHWOOD VETS& THE WELL ANIMAL CLINIC*

*“A COMPLETE CARING SERVICE FOR YOUR PET”*

*Visit us at: **www.blythwood.com* <http://www.blythwood.com/>* & **www.wellanimalclinic.com 
<http://www.wellanimalclinic.com/>*

**Comment by darius-janusauskas** [comment]
just add it in yourself :)

**Pull request closed without merging**
